### PR TITLE
UI Editor

### PR DESCRIPTION
**Pull request by Gaardsholt**
Created a UI editor as requested at https://github.com/custom-cards/upcoming-media-card/issues/22

### CODE REVIEW

**Comment by gbdavidx** [comment]
Does this fix any issues with the latest release of home-assistant?

**Comment by Gaardsholt** [comment]
Which issue?
I have just tested it on my own installation which is version 0.96.4

**Comment by maykar** [comment]
Thanks for this, will have a look as soon as I can

**Comment by maykar** [comment]
Going to work on the editor a bit more, but the actual card needs some much needed work before I actually pull this. This card was my first project and it is an absolute mess. A side effect of this is that the editor won't show live updates of config changes. So it might be a little bit before I pull this one.

**Comment by mattmattmatt** [comment]
Anything I can support with here? Would love to help set up the UI Editor, and fix what needs fixing on the way.

**Comment by maykar** [comment]
This was my very first card and also my very first coding project made over 2 years ago. It doesn't function as a card should and barely resembles what one should look like.

This causes things like the live updating of the card preview in a UI editor to not function. To be completely honest, the card needs a complete rewrite.

**Comment by maykar** [comment]
Other than the issue mentioned above, the editor is actually in pretty good shape. It needs some elements updated from paper elements to mwc since it was created before the migration to those elements. Also, since I introduced the ability to use a JSON object rather than just a JSON string for components the auto population of compatible installed components might need tweaked a bit.

**Pull request closed without merging**
